#!/bin/bash
# Clear the Terminal log screen.
clear
# Set build version
VERSION="_15-03-2013"
# Remove old modules and old zImage.
# rm kernel-pack/system/lib/modules/*.ko
rm kernel-pack/system/lib/modules/bcmdhd.ko
rm kernel-pack/system/lib/modules/cpaccess.ko
rm kernel-pack/system/lib/modules/kineto_gan.ko
rm kernel-pack/system/lib/modules/scsi_wait_scan.ko
rm kernel-pack/system/lib/modules/dma_test.ko
rm kernel-pack/system/lib/modules/reset_modem.ko
rm kernel-pack/kernel/zImage
# Copy new modules and new zImage.
# cp drivers/net/wireless/bcmdhd/bcmdhd.ko kernel-pack/system/lib/modules
# cp drivers/net/kineto_gan.ko kernel-pack/system/lib/modules
#
# cp arch/arm/boot/zImage /kernel-pack/kernel
# find . -name "*.ko" -exec cp {} /kernel-pack/system/lib/modules/ \;
#
cp arch/arm/boot/zImage kernel-pack/kernel
cp drivers/net/wireless/bcmdhd/bcmdhd.ko kernel-pack/system/lib/modules
cp arch/arm/common/cpaccess.ko cpaccess.ko kernel-pack/system/lib/modules
cp drivers/net/kineto_gan.ko kernel-pack/system/lib/modules
cp drivers/scsi/scsi_wait_scan.ko kernel-pack/system/lib/modules
cp arch/arm/mach-msm/dma_test.ko kernel-pack/system/lib/modules
cp arch/arm/mach-msm/reset_modem.ko kernel-pack/system/lib/modules
#
# Creat a zip package.
cd kernel-pack
zip -r Kernel_3.0.69_$VERSION.zip *
# Drop it to release folder
mv Kernel_3.0.69_$VERSION.zip ~/android/
